/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.v2;

import Models.Employee;
import controls.FrameDragListener;
import Models.Report;
import Models.ReportList;
import Models.Table;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ahmed
 */
public class Table_popup extends javax.swing.JFrame {

    /**
     * Creates new form Table_popup
     */
    Table table;
    Sell s;
    Report r ;
    public Table_popup() {
        initComponents();
        FrameDragListener frameDragListener = new FrameDragListener(this);
                topPanel_popup1.addMouseListener(frameDragListener);
                topPanel_popup1.addMouseMotionListener(frameDragListener);
             
    }
 public Table_popup(Table table, Sell s) {
        initComponents();
        FrameDragListener frameDragListener = new FrameDragListener(this);
                topPanel_popup1.addMouseListener(frameDragListener);
                topPanel_popup1.addMouseMotionListener(frameDragListener);
//         Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
//         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         
         topPanel_popup1.setText("Table "+table.getNumber());
         topPanel_popup1.setframes(this,s);
        this.table=table;
        this.s =s ;
        
        if(table.getState().equalsIgnoreCase("available")){
         cancel_state();
        }else{
        reserve_state();
        }
         
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        center_button5 = new controls.center_button();
        center_button6 = new controls.center_button();
        center_button7 = new controls.center_button();
        center_button8 = new controls.center_button();
        topPanel_popup1 = new controls.topPanel_popup();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 59, 55), 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        center_button5.setText("Reserve");
        center_button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                center_button5ActionPerformed(evt);
            }
        });

        center_button6.setText("Add Food");
        center_button6.setEnabled(false);
        center_button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                center_button6ActionPerformed(evt);
            }
        });

        center_button7.setText("History");
        center_button7.setEnabled(false);
        center_button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                center_button7ActionPerformed(evt);
            }
        });

        center_button8.setText("Check out");
        center_button8.setEnabled(false);
        center_button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                center_button8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(center_button8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(center_button7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(center_button6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(center_button5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(center_button5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(center_button6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(center_button7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(center_button8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel_popup1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topPanel_popup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    void reserve_state(){
         center_button5.setText("Cancel");
         center_button6.setEnabled(true);
         center_button7.setEnabled(true);
         center_button8.setEnabled(true);
         try {
            r= ReportList.getreportbytable(table.getNumber());
        } catch (SQLException ex) {
            Logger.getLogger(Table_popup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void cancel_state(){
         center_button5.setText("Reserve");
         center_button6.setEnabled(false);
         center_button7.setEnabled(false);
         center_button8.setEnabled(false);
       r= null;
    }
    private void center_button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_center_button5ActionPerformed



        if(center_button5.getText().equals("Cancel")){
            try {
                r.remove_report();
            } catch (SQLException ex) {
                Logger.getLogger(Table_popup.class.getName()).log(Level.SEVERE, null, ex);
            }
        
         cancel_state();
        s.intialize(table.getCat());
         //s.intialize(table.getCat());
        }else{
            
        try {
            // TODO add your handling code here:

            r = new Report(ReportList.getreportnumber(), table.getNumber(),table.getCat(), Employee.currentEmployee.getName());
            r.add_report();
        } catch (SQLException ex) {
            Logger.getLogger(Table_popup.class.getName()).log(Level.SEVERE, null, ex);
        }
         reserve_state();
         s.intialize(table.getCat());
       // s.intialize("normal");
         //s.intialize(table.getCat());
        }
    }//GEN-LAST:event_center_button5ActionPerformed
   
    private void center_button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_center_button6ActionPerformed
        // TODO add your handling code here:
        new Add_food(r,s).setVisible(true);
        dispose();
        s.setVisible(false);
        s.setEnabled(false);
    }//GEN-LAST:event_center_button6ActionPerformed

    private void center_button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_center_button7ActionPerformed
        // TODO add your handling code here:
        new Table_History(s,r).setVisible(true);
        dispose();
        s.setVisible(false);
        s.setEnabled(false);
    }//GEN-LAST:event_center_button7ActionPerformed

    private void center_button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_center_button8ActionPerformed
      boolean done= false;
        try {
            // TODO add your handling code here:
           done = r.close_report();
        } catch (SQLException ex) {
            Logger.getLogger(Table_popup.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(done){
         cancel_state();
        s.intialize(table.getCat());
        }
        
    }//GEN-LAST:event_center_button8ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        s.intialize(table.getCat());
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_popup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.center_button center_button5;
    private controls.center_button center_button6;
    private controls.center_button center_button7;
    private controls.center_button center_button8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private controls.topPanel_popup topPanel_popup1;
    // End of variables declaration//GEN-END:variables
}
