/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.v2;

import Models.Table;
import Models.TablesList;
import Models.Item;
import controls.TableListButton;
import controls.WrapLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseWheelListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class Tables_settings extends javax.swing.JFrame {

    /**
     * Creates new form Tables_settings
     */
    Main m;
    public MouseWheelListener ml;
    public Tables_settings() {
        initComponents();
        intialize_menu();
        intialize("normal");
        ml = jScrollPane2.getMouseWheelListeners()[0];
    }
public Tables_settings(Main m) {
        initComponents();
        this.m=m;
        intialize_menu();
        intialize("normal");
        ml = jScrollPane2.getMouseWheelListeners()[0];
        back_button1.setframes(this, m);
        home_button1.setMain(m, this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo1 = new controls.Logo();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        items_list1 = new controls.Items_list();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back_button1 = new controls.Back_button();
        home_button1 = new controls.Home_button();
        close_button1 = new controls.Close_button();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        customizedListButton2 = new controls.TableListButton();
        customizedListButton1 = new controls.TableListButton();
        customizedListButton3 = new controls.TableListButton();
        customizedListButton4 = new controls.TableListButton();
        customizedListButton5 = new controls.TableListButton();
        customizedListButton6 = new controls.TableListButton();
        customizedListButton7 = new controls.TableListButton();
        customizedListButton8 = new controls.TableListButton();
        customizedListButton9 = new controls.TableListButton();
        tableListButton1 = new controls.TableListButton();
        tableListButton2 = new controls.TableListButton();
        tableListButton3 = new controls.TableListButton();
        tableListButton4 = new controls.TableListButton();
        tableListButton5 = new controls.TableListButton();
        tableListButton6 = new controls.TableListButton();
        tableListButton7 = new controls.TableListButton();
        tableListButton8 = new controls.TableListButton();
        center_button1 = new controls.center_button();
        center_button2 = new controls.center_button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(61, 59, 55));

        jPanel2.setOpaque(false);

        logo1.setText("logo1");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 243, 243));
        jLabel1.setText("ARAME® Restaurant");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setOpaque(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        items_list1.setSelectedIndex(0);
        items_list1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                items_list1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(items_list1);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setViewportBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(243, 243, 243));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Edit Tables");

        back_button1.setText("back_button1");

        home_button1.setText("home_button1");

        close_button1.setText("close_button1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(close_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(home_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        jPanel6.setOpaque(false);
        jPanel6.add(customizedListButton2);

        customizedListButton1.setText("2");
        jPanel6.add(customizedListButton1);

        customizedListButton3.setText("3");
        jPanel6.add(customizedListButton3);

        customizedListButton4.setText("4");
        jPanel6.add(customizedListButton4);
        jPanel6.add(customizedListButton5);
        jPanel6.add(customizedListButton6);
        jPanel6.add(customizedListButton7);
        jPanel6.add(customizedListButton8);
        jPanel6.add(customizedListButton9);
        jPanel6.add(tableListButton1);
        jPanel6.add(tableListButton2);
        jPanel6.add(tableListButton3);
        jPanel6.add(tableListButton4);
        jPanel6.add(tableListButton5);
        jPanel6.add(tableListButton6);
        jPanel6.add(tableListButton7);
        jPanel6.add(tableListButton8);

        jPanel6.setLayout(new WrapLayout(0,5,5));

        jScrollPane2.setViewportView(jPanel6);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setViewportBorder(null);

        center_button1.setText("Add Custom Table");
        center_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                center_button1ActionPerformed(evt);
            }
        });

        center_button2.setText("Add Table");
        center_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                center_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(center_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(center_button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(center_button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(center_button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void items_list1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_items_list1ValueChanged
        // TODO add your handling code here:
        if(items_list1.getSelectedIndex()>=0)
        intialize(items_list1.getSelectedValue().getText());
    }//GEN-LAST:event_items_list1ValueChanged
   public  int getnum(){
        int num =0;
        try{
            String input = JOptionPane.showInputDialog("Enter Table number :") ;
            if(input==null)
                return 0;
            num= Integer.parseInt(input);
        
        }catch(Exception e){
             return -1;
        }
      return num;
    }
    private void center_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_center_button1ActionPerformed
      int num=getnum();
        while(num<0){
        num= getnum();
      } 
        if(num==0)
            return;
         try {
            // TODO add your handling code here:
            Table t = new Table(num,"available",items_list1.getSelectedValue().getText() );
            if(t.isValid()){
                t.add();
                intialize(t.getCat());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tables_settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_center_button1ActionPerformed

    private void center_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_center_button2ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Table t = new Table("available",items_list1.getSelectedValue().getText() );
            if(t.isValid()){
                t.add();
                intialize(t.getCat());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tables_settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_center_button2ActionPerformed
 void intialize_menu(){
     DefaultListModel<Item> listModel = new DefaultListModel<>();
   List<Item> items = new ArrayList<>();
        
         items.add(new Item("Normal"));
         items.add(new Item("Family"));
         items.add(new Item("Couple"));
         items.add(new Item("Vip"));
        for(Item i :items)
            listModel.addElement(i);
        items_list1.setModel(listModel);
        items_list1.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        items_list1.setVisibleRowCount(-1);
        items_list1.setSelectedIndex(0);
        
        //create the list
       
 
 }
 void  intialize (String cat){
      jPanel6.revalidate();
     jPanel6.removeAll();
     jPanel6.repaint();
    // topPanel1.setText(cat);
     jPanel6.setBackground(Color.yellow);
     
  try {
      
            for(Table t :TablesList.getTables()){
                if(t.getCat().equalsIgnoreCase(cat)){
                    TableListButton b = new TableListButton(t);
                
                jPanel6.add(b);
                Tables_settings s = this;
                b.addActionListener(new ActionListener() {
                    
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        jScrollPane2.removeMouseWheelListener(jScrollPane2.getMouseWheelListeners()[0]);
                       pop_edit p = new pop_edit(s,t);
                       p.setLocationRelativeTo(b);
                       p.setVisible(true);
                       
                    }
                });
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sell.class.getName()).log(Level.SEVERE, null, ex);
        }
   
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tables_settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tables_settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tables_settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tables_settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tables_settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.Back_button back_button1;
    private controls.center_button center_button1;
    private controls.center_button center_button2;
    private controls.Close_button close_button1;
    private controls.TableListButton customizedListButton1;
    private controls.TableListButton customizedListButton2;
    private controls.TableListButton customizedListButton3;
    private controls.TableListButton customizedListButton4;
    private controls.TableListButton customizedListButton5;
    private controls.TableListButton customizedListButton6;
    private controls.TableListButton customizedListButton7;
    private controls.TableListButton customizedListButton8;
    private controls.TableListButton customizedListButton9;
    private controls.Home_button home_button1;
    private controls.Items_list items_list1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private controls.Logo logo1;
    private controls.TableListButton tableListButton1;
    private controls.TableListButton tableListButton2;
    private controls.TableListButton tableListButton3;
    private controls.TableListButton tableListButton4;
    private controls.TableListButton tableListButton5;
    private controls.TableListButton tableListButton6;
    private controls.TableListButton tableListButton7;
    private controls.TableListButton tableListButton8;
    // End of variables declaration//GEN-END:variables
}
