/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.v2;

import Models.Order;
import Models.OrderList;
import Models.Report;
import Models.ReportList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class Table_History extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    Sell s;
    Report r;
    Table_History h;
   
    public Table_History() {
        initComponents();
        table_panel1.Tax.text.setText("Tax");
        table_panel1.Service.text.setText("Service(20%)");
        ((DefaultTableModel)table_panel1.Table.getModel()).setRowCount(1);
        
    }

    public Table_History(Sell s, Report r) {
        initComponents();
        this.s = s;
        this.r = r;
        table_panel1.Tax.text.setText("Tax");
        table_panel1.Service.text.setText("Service(20%)");
        h=this;
        TableNum.setText("Table "+r.getTableNum()+" ("+r.getTableType()+")");
        intialize();
        handle_actions();
    }
    
void intialize (){
        
        DefaultTableModel model = (DefaultTableModel)table_panel1.Table.getModel();
        model.setRowCount(1);
        
        try {
            r= ReportList.getreport(r.getId());
        } catch (SQLException ex) {
            Logger.getLogger(Table_History.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(r.getOrders().size()>0)
            model.removeRow(0);
        for(Order o :r.getOrders()){
         model.addRow(new Object[]{o.getProduct(),o.getSize(),o.getNum(),o.getPrice(),o.getTotal(),o.getTime()});
         
        }
       table_panel1.Subtotal.value.setText(String.valueOf(r.getCash()));
       table_panel1.Tax.value.setText(String.valueOf(r.getTax()));
       table_panel1.Service.value.setText(String.valueOf(r.getService()));
      
       table_panel1.Total.value.setText(String.valueOf(r.getPayed()));
       table_panel1.Remove.setEnabled(false);
       
    }
void handle_actions(){
    back_button1.setframes(this, s);
    home_button1.setMain(s.m, this);
    
    table_panel1.Add.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                new Add_food(r,h).setVisible(true);
                
            }
        });
       table_panel1.Checkout.addActionListener(new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            boolean done = false;
            try {
            // TODO add your handling code here:
            done = r.close_report();
        } catch (SQLException ex) {
            Logger.getLogger(Table_popup.class.getName()).log(Level.SEVERE, null, ex);
        }
         if(done){
        s.intialize(r.getTableType());
        dispose();
        s.setEnabled(true);
        s.setVisible(true);
         }
        }
    });
       table_panel1.Remove.addActionListener(new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            try {
               
                r.Remove_order(table_panel1.Table.getSelectedRow());
                r = ReportList.getreport(r.getId());
                intialize();
            } catch (SQLException ex) {
                Logger.getLogger(Table_History.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    });
       table_panel1.Switch.addActionListener(new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            new Switch(h, r).setVisible(true);
            h.setEnabled(false);
        }
    });
      table_panel1.Table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

        @Override
        public void valueChanged(ListSelectionEvent lse) {
            if(table_panel1.Table.getSelectedRow()>=0)
                table_panel1.Remove.setEnabled(true);
            else
                table_panel1.Remove.setEnabled(false);
        }
    });
      
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TableNum = new javax.swing.JLabel();
        close_button1 = new controls.Close_button();
        home_button1 = new controls.Home_button();
        back_button1 = new controls.Back_button();
        jPanel2 = new javax.swing.JPanel();
        table_panel1 = new restaurant.v2.Table_panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 198, 198)));

        TableNum.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TableNum.setForeground(new java.awt.Color(82, 82, 82));
        TableNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TableNum.setText("Table 1");

        close_button1.setText("close_button1");

        home_button1.setText("home_button1");

        back_button1.setText("back_button1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TableNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableNum)
                    .addComponent(home_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        table_panel1.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(table_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(table_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        requestFocus();
        table_panel1.Table.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel TableNum;
    private controls.Back_button back_button1;
    private controls.Close_button close_button1;
    private controls.Home_button home_button1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private restaurant.v2.Table_panel table_panel1;
    // End of variables declaration//GEN-END:variables
}
