/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.v2;

/**
 *
 * @author ahmed
 */
public class TopPanel_popup extends javax.swing.JPanel {

    /**
     * Creates new form TopPanel_popup
     */
    public TopPanel_popup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableNum = new javax.swing.JLabel();
        dispose_button1 = new controls.Dispose_button();

        setBackground(new java.awt.Color(61, 59, 55));

        TableNum.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TableNum.setForeground(new java.awt.Color(255, 255, 255));
        TableNum.setText("Table 1");

        dispose_button1.setText("dispose_button1");
        dispose_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispose_button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(TableNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(dispose_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dispose_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableNum))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dispose_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispose_button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dispose_button1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TableNum;
    private controls.Dispose_button dispose_button1;
    // End of variables declaration//GEN-END:variables
}
